# **Tensor Aggregation**

In [3]:
import torch
x=torch.arange(0,10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
print(torch.min(x))
print(torch.max(x))
#print(torch.mean(x))
# mean(): could not infer output dtype.
# Input dtype must be either a floating point or complex dtype. Got: Long
print(torch.mean(x.type(torch.float32)))

tensor(0)
tensor(9)
tensor(4.5000)


In [9]:
print(x.sum())


tensor(45)


In [14]:
print(torch.argmin(x))# positional min and max
print(torch.argmax(x)) #index positiion of min and max value occuring

tensor(0)
tensor(9)


# **Reshaping, viewing ,Squeze , Permute and stacking Tensors**
https://pytorchguide.netlify.app/chapter-01/reshape-stack-squeeze-tensors/

In [25]:
import torch
y=torch.arange(1,11)
y,y.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [26]:
#Add and extra dimension
y_reshaped=y.reshape(5,2)#5*2=10
y_reshaped,y_reshaped.shape


(tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]),
 torch.Size([5, 2]))

In [27]:
#change the view
# z shares memory as what y does ,changing z changes y
z=y.view(2,5)
z,z.shape

(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 torch.Size([2, 5]))

In [34]:
#stack tensors on top of each other
y_stacked=torch.stack([y,y,y,y],dim=0)
print(y_stacked)
y_vstacked=torch.vstack([y,y,y,y])
print(y_vstacked)
y_hstacked=torch.hstack([y,y,y,y])
print(y_hstacked)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1,  2,  3,  4,  5,  6,  7,  8,
         9, 10,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1,  2,  3,  4,  5,  6,
         7,  8,  9, 10])


In [44]:
#squueze and unsqueeze
w=y_hstacked.squeeze()
print(w)
print("shape: "+ str(w.shape))
# puts it in one dimension , removes all one dimension to avoid dimension
# mismatch
q=w.unsqueeze(dim=0)
print(q)
print( "shape: "+str(q.shape))

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1,  2,  3,  4,  5,  6,  7,  8,
         9, 10,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1,  2,  3,  4,  5,  6,
         7,  8,  9, 10])
shape: torch.Size([40])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1,  2,  3,  4,  5,  6,  7,  8,
          9, 10,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1,  2,  3,  4,  5,  6,
          7,  8,  9, 10]])
shape: torch.Size([1, 40])


In [45]:
#permute = swap the dimensions
x_2=torch.rand(224,224,3) #RGB or HWL
x_permuted=x_2.permute(2,0,1)
print(x_permuted.shape)

torch.Size([3, 224, 224])


# **Indexing**

In [46]:
#selecting data from tensors
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [50]:
x[0][0][0]

tensor(1)